In [10]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

1.8.0


In [11]:
from tensorflow.contrib.learn.python.learn.datasets import base
# Data files
IRIS_TRAINING='iris_training.csv'
IRIS_TEST='iris_test.csv'
# Load datasets
training_set=base.load_csv_with_header(filename=IRIS_TRAINING,features_dtype=np.float32,target_dtype=np.int)
test_set=base.load_csv_with_header(filename=IRIS_TEST,features_dtype=np.float32,target_dtype=np.int)
print(training_set.data)
print(training_set.target)

[[6.4 2.8 5.6 2.2]
 [5.  2.3 3.3 1. ]
 [4.9 2.5 4.5 1.7]
 [4.9 3.1 1.5 0.1]
 [5.7 3.8 1.7 0.3]
 [4.4 3.2 1.3 0.2]
 [5.4 3.4 1.5 0.4]
 [6.9 3.1 5.1 2.3]
 [6.7 3.1 4.4 1.4]
 [5.1 3.7 1.5 0.4]
 [5.2 2.7 3.9 1.4]
 [6.9 3.1 4.9 1.5]
 [5.8 4.  1.2 0.2]
 [5.4 3.9 1.7 0.4]
 [7.7 3.8 6.7 2.2]
 [6.3 3.3 4.7 1.6]
 [6.8 3.2 5.9 2.3]
 [7.6 3.  6.6 2.1]
 [6.4 3.2 5.3 2.3]
 [5.7 4.4 1.5 0.4]
 [6.7 3.3 5.7 2.1]
 [6.4 2.8 5.6 2.1]
 [5.4 3.9 1.3 0.4]
 [6.1 2.6 5.6 1.4]
 [7.2 3.  5.8 1.6]
 [5.2 3.5 1.5 0.2]
 [5.8 2.6 4.  1.2]
 [5.9 3.  5.1 1.8]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [6.3 2.3 4.4 1.3]
 [5.1 2.5 3.  1.1]
 [6.4 3.2 4.5 1.5]
 [6.8 3.  5.5 2.1]
 [6.2 2.8 4.8 1.8]
 [6.9 3.2 5.7 2.3]
 [6.5 3.2 5.1 2. ]
 [5.8 2.8 5.1 2.4]
 [5.1 3.8 1.5 0.3]
 [4.8 3.  1.4 0.3]
 [7.9 3.8 6.4 2. ]
 [5.8 2.7 5.1 1.9]
 [6.7 3.  5.2 2.3]
 [5.1 3.8 1.9 0.4]
 [4.7 3.2 1.6 0.2]
 [6.  2.2 5.  1.5]
 [4.8 3.4 1.6 0.2]
 [7.7 2.6 6.9 2.3]
 [4.6 3.6 1.  0.2]
 [7.2 3.2 6.  1.8]
 [5.  3.3 1.4 0.2]
 [6.6 3.  4.4 1.4]
 [6.1 2.8 4.

In [12]:
feature_name='flower_features'
feature_columns=[tf.feature_column.numeric_column(feature_name,shape=[4])]

classifier = tf.estimator.LinearClassifier(feature_columns=feature_columns,n_classes=3,model_dir='./tmp/iris_model')


INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './tmp/iris_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000024E634C9358>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [13]:
def input_fn(dataset):
    def _fn():
        features={feature_name:tf.constant(dataset.data)}
        label=tf.constant(dataset.target)
        return features,label
    return _fn

print(input_fn(training_set)())

({'flower_features': <tf.Tensor 'Const_2:0' shape=(120, 4) dtype=float32>}, <tf.Tensor 'Const_3:0' shape=(120,) dtype=int32>)


In [14]:
classifier.train(input_fn=input_fn(training_set),steps=1000)
print('fit done')

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./tmp/iris_model\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1001 into ./tmp/iris_model\model.ckpt.
INFO:tensorflow:loss = 13.050381, step = 1000
INFO:tensorflow:global_step/sec: 553.965
INFO:tensorflow:loss = 12.516876, step = 1100 (0.181 sec)
INFO:tensorflow:global_step/sec: 748.263
INFO:tensorflow:loss = 12.057024, step = 1200 (0.135 sec)
INFO:tensorflow:global_step/sec: 765.41
INFO:tensorflow:loss = 11.6558695, step = 1300 (0.131 sec)
INFO:tensorflow:global_step/sec: 737.253
INFO:tensorflow:loss = 11.302315, step = 1400 (0.135 sec)
INFO:tensorflow:global_step/sec: 777.274
INFO:tensorflow:loss = 10.9879465, step = 1500 (0.129 sec)
INFO:tensorflow:global_step/sec: 789.498
INFO:tensorflow:loss = 10.7

In [15]:
accuracy_score=classifier.evaluate(input_fn=input_fn(test_set),steps=100)['accuracy']
print('\nAccuracy:{0:f}'.format(accuracy_score))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-06-05-03:36:48
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./tmp/iris_model\model.ckpt-2000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [10/100]
INFO:tensorflow:Evaluation [20/100]
INFO:tensorflow:Evaluation [30/100]
INFO:tensorflow:Evaluation [40/100]
INFO:tensorflow:Evaluation [50/100]
INFO:tensorflow:Evaluation [60/100]
INFO:tensorflow:Evaluation [70/100]
INFO:tensorflow:Evaluation [80/100]
INFO:tensorflow:Evaluation [90/100]
INFO:tensorflow:Evaluation [100/100]
INFO:tensorflow:Finished evaluation at 2018-06-05-03:36:48
INFO:tensorflow:Saving dict for global step 2000: accuracy = 0.96666664, average_loss = 0.08876687, global_step = 2000, loss = 2.6630063

Accuracy:0.966667


In [16]:
feature_spec={'flower_features':tf.FixedLenFeature(shape=[4],dtype=np.float32)}

serving_fn=tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)

classifier.export_savedmodel(export_dir_base='./tmp/iris_model/export',serving_input_receiver_fn=serving_fn)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Signatures INCLUDED in export for Classify: ['serving_default', 'classification']
INFO:tensorflow:Signatures INCLUDED in export for Regress: None
INFO:tensorflow:Signatures INCLUDED in export for Predict: ['predict']
INFO:tensorflow:Restoring parameters from ./tmp/iris_model\model.ckpt-2000
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: b"./tmp/iris_model/export\\temp-b'1528169808'\\saved_model.pb"


b'./tmp/iris_model/export\\1528169808'

In [21]:
# use dnn classifier
classifier_dnn = tf.estimator.DNNClassifier(feature_columns=feature_columns,
                                            n_classes=3,hidden_units=[100,50,25,12],
                                            optimizer=tf.train.ProximalAdagradOptimizer(
                                                learning_rate=0.1,
                                                l1_regularization_strength=0.001),
                                            activation_fn=tf.nn.elu,
                                            dropout=0.4,
                                            model_dir='./tmp/iris_model_dnn')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './tmp/iris_model_dnn', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000024E7407F3C8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
